apiVersion: v1
kind: Service
metadata:
  name: staging-nodejs-app-service
  labels:
    app: staging-nodejs-app
spec:
  selector:
    app: staging-nodejs-app
  ports:
  - port: 3000  # External port
    targetPort: 8080  # Container port