apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: crud-api-hpa
  namespace: staging-nodejs-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: production-nodejs-app-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50