apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-nodejs-app-deployment
  labels:
    app: staging-nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staging-nodejs-app
  template:
    metadata:
      labels:
        app: staging-nodejs-app
    spec:
      containers:
      - name: staging-nodejs-app
      image: dummy-repository/staging-nodejs-app
      ports:
      - containerPort: 8080
      env:
        - name: DB_HOST
          value: postgres
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: 123
        - name: DB_NAME
          value: testdb